POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpMiIsImlkIjoiNWZhNTJkMjRhMDdkNjAyZTQ0MmMxYzg1IiwiaWF0IjoxNjA0NjYwNTQzfQ.aOLZH0ymtQc-fu2Qx7lZByrhRhzqS4aFSaoOca3yqbU


{
    "title": "4.19",
    "author": "Mee",
    "url": "www.test.com",
    "likes": "0"
}