POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpMyIsImlkIjoiNWZhNTM5MWU3OGMyODkyMWQ0NjRmNmM3IiwiaWF0IjoxNjA0NjYzNjAwfQ.mEZD3Q2Pgomf6kgiVFjeZC2JrdOz1EOQzZuqBEdMYy0


{
    "title": "4.20",
    "author": "Meee",
    "url": "www.test.com",
    "likes": "0"
}